apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/brianwcook/sagano?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.reddat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && ".tekton/centos-tier-0-stream9-push.yaml".pathChanged() && target_branch == "main"
  labels:
    appstudio.openshift.io/application: sagano
    appstudio.openshift.io/component: centos-tier-0-stream9
    pipelines.appstudio.openshift.io/type: build
  name: centos-tier-0-stream9-on-push
  namespace: project-sagano-tenant
spec:
  params:
  - name: image-file
    value: centos-tier-0-stream9.yaml
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/project-sagano-tenant/sagano/centos-tier-0-stream9:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: ostree-build
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: workspace-arm64
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
    - name: workspace-s390x
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
    - name: workspace-ppc64le
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
